# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f2035654911a646397ace740376c1a4edec58bebae40f300a2bca5bc6de07fd48c5117d35e53a2d14cb59c9a643c1b2c8f36d592b67bb61a4c2b407f41f118

test:
  secret_key_base: b57492060e711727eacf906cad1ddd1e4e8093733dbf081fbbe3a130d7d045ad669591dd4be11c81f3e417e71774d5ecc01a4b28c1f2c30673284f3acba26f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
